remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Yu's Garden Of Thoughts
description: For itemizing ideas, difficulties and maybe source-code-study "encountered" by Fish Zhang as a graphics developer.